### ISSUE TITLE
If adding both of .so to /.local/lib/deadbeef, menu has double entry of each option

### ISSUE THREAD

**Issue by DanteDragan** [kpcee/deadbeef-playlist-manager#3]
If I delete one of the .so, plugin works properly.
![screenshot](https://github.com/kpcee/deadbeef-playlist-manager/assets/91615147/3b2880de-3c0f-4049-8077-14c977fe7d5f)

**Comment by kpcee** [comment]
I have revised the instructions, you have to choose one of the two versions. Depending on whether you want to use GTK2 or GTK3.
